# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: .


  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
