version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is is db folder
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: world
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: securedb
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'

    build: db/.
    command: --mysql_native_password=ON
    restart: always